package ps.g49.socialroutingservice.repositories

import ps.g49.socialroutingservice.model.Person

interface PersonRepository  {

    /**
     * @param id is generated by the database or the email
     */
    fun findPersonById(id : String) : Person

}