package ps.g49.socialroutingservice.repositories

import ps.g49.socialroutingservice.model.Person

interface PersonRepository {

    /**
     * @param identifier is generated by the database or the email
     */
    fun findPersonById(identifier: Int): Person

    fun create(name : String, email : String)

    fun delete(identifier: Int)

}